version: "3.8"

services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
     - db_data:/var/lib/postgresql/data
    networks:
      - order_service_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 3s
      retries: 5

  order_service:
    build: .
    ports:
     - "${APP_PORT}:8080"
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      USER_SERVICE_URL: ${USER_SERVICE_URL}
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - order_service_network

networks:
  order_service_network:
    driver: bridge

volumes:
  db_data:
    name: ${SERVICE_NAME}_db_data